# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "ansible" do |ansible|
    ansible.vm.hostname = "ansible01"
    ansible.vm.network "private_network", ip: "192.168.100.20"
    ansible.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  config.vm.define "web" do |web|
    web.vm.hostname = "web01"
    web.vm.network "private_network", ip: "192.168.100.20"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  config.vm.define "zabbix" do |zabbix|
    zabbix.vm.hostname = "zabbix01"
    zabbix.vm.network "private_network", ip: "192.168.100.20"
    zabbix.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum install epel-release -y
    yum install ansible git -y
    git clone https://github.com/hiyokotaisa/ansible_playbooks.git
    cd ansible_playbooks/bootstrap/
    ansible-playbook -i hosts sshd_config.yml
  SHELL
  config.ssh.insert_key = false
end
