# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  # Webサーバーの設定
  config.vm.define "web" do |web|
    web.vm.hostname = "web01"
    web.vm.network "private_network", ip: "192.168.100.20"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end
  
  # Zabbixノードの設定
  config.vm.define "zabbix" do |zabbix|
    zabbix.vm.hostname = "zabbix01"
    zabbix.vm.network "private_network", ip: "192.168.100.21"
    zabbix.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
  end
  
  # Ansibleノードの設定
  config.vm.define "ansible" do |ansible|
    ansible.vm.hostname = "ansible01"
    ansible.vm.network "private_network", ip: "192.168.100.10"
    ansible.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    # 各ノードへSSH鍵を登録 (Ansibleノードのみ)
    ansible.vm.provision "shell", privileged: false, inline: <<-SHELL
      ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa
      sshpass -p "vagrant" ssh-copy-id -i ~/.ssh/id_rsa.pub -o "StrictHostKeyChecking no" 192.168.100.10
      sshpass -p "vagrant" ssh-copy-id -i ~/.ssh/id_rsa.pub -o "StrictHostKeyChecking no" 192.168.100.20
      sshpass -p "vagrant" ssh-copy-id -i ~/.ssh/id_rsa.pub -o "StrictHostKeyChecking no" 192.168.100.21
    SHELL
  end

  # 全体共通設定
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo yum install epel-release -y
    sudo yum install ansible git -y
    git clone https://github.com/hiyokotaisa/ansible_playbooks.git
    cd ansible_playbooks/bootstrap/
    ansible-playbook -i hosts sshd_config.yml
  SHELL
  config.ssh.insert_key = false
end
