# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "vyos" do |vyos|
    vyos.vm.box = "higebu/vyos"
    vyos.vm.network "private_network", ip: "192.168.100.20"
    vyos.vm.network "private_network", type: "dhcp"
    vyos.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  # Ansibleノードの設定
  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "centos/7"
    ansible.vm.hostname = "ansible01"
    ansible.vm.network "private_network", ip: "192.168.100.10"
    ansible.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    ansible.vm.provision "shell", privileged: false, inline: <<-SHELL
      ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa
      sudo yum install epel-release -y
      sudo yum install ansible git -y
      git clone https://github.com/hiyokotaisa/ansible_playbooks.git
    SHELL
  end
end
