# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "higebu/vyos"
  config.vm.network "private_network", ip: "192.168.100.10"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

end
