---
- name: Install Nginx
  hosts: web
  vars:
    ansible_become: yes
    ansible_become_method: sudo

  tasks:
    - name: Change Hostname
      hostname:
        name: web01

    - name: Install Nginx
      yum:
        name: nginx
        state: latest

    - name: Copy contents
      copy:
        src: ./contents/
        dest: /usr/share/nginx/html
        owner: vagrant

    - name: Start Nginx
      systemd:
        state: started
        name: nginx
